# Prometheus configuration file
global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'windows_servers'
    static_configs:
      - targets:
          - '192.168.0.139:9182'
        labels:
          server_name: 'LOCALHOST'
      
      - targets:
          - '192.168.50.254:9182'
        labels:
          server_name: 'Siva-Machine'
       
      # 1 HO Server
      - targets:
          - 'WIN-TK201B2EL0C:9182'
        labels:
          server_name: 'DAIVELHO-SERVER'
      
      # 2 Cumbum Server
      - targets:
          - '10.0.205.2:9182'
        labels:
          server_name: 'CUMBUM-SERVER'
      
      # 3 SIVAKI Server
      - targets:
          - '10.0.203.2:9182'
        labels:
          server_name: 'SIVAKI-SERVER'

      # 4 NAGERCOIL Server
      - targets:
          - '10.0.204.2:9182'
        labels:
          server_name: 'NAGERCOIL-SERVER'

      # TIRUNELVELI Server
      - targets:
          - '10.0.202.2:9182'
        labels:
          server_name: 'TIRUNELVELI-SERVER'

      # TUTICORIN Server
      - targets:
          - '10.0.201.2:9182'
        labels:
          server_name: 'TUTICORIN-SERVER'

      # THENI Server
      - targets:
          - '10.0.206.3:9182'
        labels:
          server_name: 'THENI-SERVER'

      # PALANI Server
      - targets:
          - '10.0.208.2:9182'
        labels:
          server_name: 'PALANI-SERVER'

      # ARUPUKOTTAI Server
      - targets:
          - '10.0.209.2:9182'
        labels:
          server_name: 'ARUPUKOTTAI-SERVER'

      